### ISSUE TITLE
Problem installing helper tool

### ISSUE THREAD

**Issue by nilskoll** [miyako/4d-plugin-purge#1]
Unable to successfully install the purge.HelperTool.
When launching the Purge Helper.app from the Plugin, the console displays:
smd[360]: App "com.apple.bsd.purgehelper" did not pass helper check "com.apple.bsd.purge.HelperTool".
Purge Helper[5404]: Failed to bless helper. Error: Error Domain=CFErrorDomainLaunchd Code=4 "(null)"

OS version: Mac OS X El Capitan 10.11.5

**Comment by miyako** [comment]
strange, I've recompiled the plugin just now, could you try again?

**Comment by nilskoll** [comment]
Just tried it and it installed the helper tool successfully and I tested it using the purge database and it worked. Thanks for the quick response!
The app wasn't code signed, but I guess you know that.

**Comment by miyako** [comment]
or maybe it needed to be signed using the latest OS X...who knows...
